
import java.math.BigDecimal;
import java.math.MathContext;
import java.math.RoundingMode;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author PhongFPT
 */
public class MyCalculator extends javax.swing.JFrame {

    /**
     * Creates new form MyCalculatorLP0022
     */
    CalculatorLogic logic;
    boolean canInputNewNumber = true;
    boolean isInputingNumber = false;
    boolean isPressEqualForCal = false;
    boolean divideByZero = false;
    String bufferScreenText=null;
    public MyCalculator() {
        initComponents();
        logic = new CalculatorLogic();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtScreen = new javax.swing.JTextField();
        btMC = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt0 = new javax.swing.JButton();
        btMR = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        btDot = new javax.swing.JButton();
        btMplus = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        btChangeSign = new javax.swing.JButton();
        btMminus = new javax.swing.JButton();
        btDivide = new javax.swing.JButton();
        btMultiply = new javax.swing.JButton();
        btMinus = new javax.swing.JButton();
        btPlus = new javax.swing.JButton();
        btSqrt = new javax.swing.JButton();
        btPercent = new javax.swing.JButton();
        bt1OverX = new javax.swing.JButton();
        btEqual = new javax.swing.JButton();
        btC = new javax.swing.JButton();
        btCE = new javax.swing.JButton();
        btMS = new javax.swing.JButton();
        btClearLastNum = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtScreen.setEditable(false);
        txtScreen.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtScreen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtScreen.setText("0");

        btMC.setText("MC");
        btMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMCActionPerformed(evt);
            }
        });

        bt7.setText("7");
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });

        bt4.setText("4");
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });

        bt1.setText("1");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        bt0.setText("0");
        bt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt0ActionPerformed(evt);
            }
        });

        btMR.setText("MR");
        btMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMRActionPerformed(evt);
            }
        });

        bt8.setText("8");
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });

        bt5.setText("5");
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });

        bt2.setText("2");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        btDot.setText(".");
        btDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDotActionPerformed(evt);
            }
        });

        btMplus.setText("M+");
        btMplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMplusActionPerformed(evt);
            }
        });

        bt9.setText("9");
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });

        bt6.setText("6");
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });

        bt3.setText("3");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });

        btChangeSign.setText("+/-");
        btChangeSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChangeSignActionPerformed(evt);
            }
        });

        btMminus.setText("M-");
        btMminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMminusActionPerformed(evt);
            }
        });

        btDivide.setText("÷");
        btDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDivideActionPerformed(evt);
            }
        });

        btMultiply.setText("X");
        btMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMultiplyActionPerformed(evt);
            }
        });

        btMinus.setText("-");
        btMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMinusActionPerformed(evt);
            }
        });

        btPlus.setText("+");
        btPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPlusActionPerformed(evt);
            }
        });

        btSqrt.setText("√");
        btSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSqrtActionPerformed(evt);
            }
        });

        btPercent.setText("%");
        btPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPercentActionPerformed(evt);
            }
        });

        bt1OverX.setText("1/x");
        bt1OverX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1OverXActionPerformed(evt);
            }
        });

        btEqual.setText("=");
        btEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEqualActionPerformed(evt);
            }
        });

        btC.setText("C");
        btC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCActionPerformed(evt);
            }
        });

        btCE.setText("CE");
        btCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCEActionPerformed(evt);
            }
        });

        btMS.setText("MS");
        btMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMSActionPerformed(evt);
            }
        });

        btClearLastNum.setText("←");
        btClearLastNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearLastNumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btClearLastNum, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btCE, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btC, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btChangeSign, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bt0, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btDot, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bt7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btMC, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btMR, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bt8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bt9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bt6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btMS, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btMplus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bt1OverX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btMminus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSqrt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btPercent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btMR, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btMS, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btMplus, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btMC, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btChangeSign, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btC, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btCE, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btClearLastNum, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(bt8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bt7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bt9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bt6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bt1OverX, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(btPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btDot, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(btEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addComponent(bt0, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btMminus, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt0ActionPerformed
        // TODO add your handling code here:
        pressNumber("0");
    }//GEN-LAST:event_bt0ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
        pressNumber("1");
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
        pressNumber("2");
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
        pressNumber("3");
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        // TODO add your handling code here:
        pressNumber("4");
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        // TODO add your handling code here:
        pressNumber("5");
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        // TODO add your handling code here:
        pressNumber("6");
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        // TODO add your handling code here:
        pressNumber("7");
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        // TODO add your handling code here:
        pressNumber("8");
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
        // TODO add your handling code here:
        pressNumber("9");
    }//GEN-LAST:event_bt9ActionPerformed

    private void btDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDotActionPerformed
        // TODO add your handling code here:
        String screen = txtScreen.getText();
        if (!screen.contains(".")) {
            screen += ".";
        }
        txtScreen.setText(screen);
    }//GEN-LAST:event_btDotActionPerformed

    private void btPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPlusActionPerformed
        // TODO add your handling code here:
        pressOperator("+");


    }//GEN-LAST:event_btPlusActionPerformed

    private void btMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMinusActionPerformed
        // TODO add your handling code here:
        pressOperator("-");
    }//GEN-LAST:event_btMinusActionPerformed

    private void btMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMultiplyActionPerformed
        // TODO add your handling code here:
        pressOperator("*");
    }//GEN-LAST:event_btMultiplyActionPerformed

    private void btDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDivideActionPerformed
        // TODO add your handling code here:
        pressOperator("/");
    }//GEN-LAST:event_btDivideActionPerformed

    private void btEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEqualActionPerformed
        // TODO add your handling code here:
        canInputNewNumber = true;
        if (divideByZero) {
            setDefaultSetting();
            divideByZero = false;
        }
        if (isInputingNumber) {
            isInputingNumber = false;
            if(bufferScreenText!=null){
                logic.getData(bufferScreenText);
                bufferScreenText=null;
            }else{
                logic.getData(txtScreen.getText());
            }
            
            if (logic.getNum1() != null && logic.getNum2() != null && logic.getOperator() != null) {
                try {
                    logic.calculate();
                    isPressEqualForCal = true;
                    String result = removeRedundantZeroAfterDot(logic.getResult().toString());
                    txtScreen.setText(result);
                    logic.setNum2(null);
                    logic.setNum1(null);
                    logic.setResult(null);
                    logic.setFirstCalculate(true);
                } catch (ArithmeticException e) {
                    divideByZero = true;
                    txtScreen.setText("ERROR");
                }

            }
        }


    }//GEN-LAST:event_btEqualActionPerformed

    private void btSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSqrtActionPerformed
        // TODO add your handling code here:
        canInputNewNumber = true;
        String screen = txtScreen.getText();
        if (screen.contains("-")) {
            bufferScreenText=txtScreen.getText();
            txtScreen.setText("ERROR");
        } else {
            BigDecimal screenNumber = new BigDecimal(screen);
            double sqrt = Math.sqrt(screenNumber.doubleValue());
            screenNumber = new BigDecimal(sqrt);
            screen = screenNumber.round(new MathContext(4)).toString();
            txtScreen.setText(screen);
        }
    }//GEN-LAST:event_btSqrtActionPerformed

    private void btPercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPercentActionPerformed
        // TODO add your handling code here:
        canInputNewNumber = true;
        String screen = txtScreen.getText();
        BigDecimal screenNumber = new BigDecimal(screen);
        screenNumber = screenNumber.divide(new BigDecimal("100"));
        txtScreen.setText(screenNumber.toString());
    }//GEN-LAST:event_btPercentActionPerformed

    private void bt1OverXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1OverXActionPerformed
        // TODO add your handling code here:
        canInputNewNumber = true;
        String screen = txtScreen.getText();
        
        if (screen.equals("0")) {
            txtScreen.setText("ERROR");
            divideByZero=true;
        } else {
            BigDecimal screenNumber = new BigDecimal(screen);
            screenNumber = new BigDecimal("1").divide(screenNumber, 4, RoundingMode.CEILING);
            String result = removeRedundantZeroAfterDot(screenNumber.toString());
            txtScreen.setText(result);
        }

    }//GEN-LAST:event_bt1OverXActionPerformed

    private void btChangeSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChangeSignActionPerformed
        // TODO add your handling code here:
        String screen = txtScreen.getText();
        if (screen.contains("-")) {
            screen = screen.replace("-", "");
        } else {
            screen = "-" + screen;
        }
        txtScreen.setText(screen);
    }//GEN-LAST:event_btChangeSignActionPerformed

    private void btMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMCActionPerformed
        // TODO add your handling code here:
        canInputNewNumber = true;
        logic.setMemory(new BigDecimal("0"));
    }//GEN-LAST:event_btMCActionPerformed

    private void btMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMRActionPerformed
        // TODO add your handling code here:
        canInputNewNumber = true;
        String screen=  removeRedundantZeroAfterDot(logic.getMemory().toString());
        txtScreen.setText(screen);
    }//GEN-LAST:event_btMRActionPerformed

    private void btMplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMplusActionPerformed
        // TODO add your handling code here:
        canInputNewNumber = true;
        if (!txtScreen.getText().equals("ERROR")) {
            logic.setMemory(logic.getMemory().add(new BigDecimal(txtScreen.getText())));
        }
    }//GEN-LAST:event_btMplusActionPerformed

    private void btMminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMminusActionPerformed
        // TODO add your handling code here:
        canInputNewNumber = true;
        if (!txtScreen.getText().equals("ERROR")) {
            logic.setMemory(logic.getMemory().subtract(new BigDecimal(txtScreen.getText())));
        }
    }//GEN-LAST:event_btMminusActionPerformed

    private void btMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMSActionPerformed
        // TODO add your handling code here:
        canInputNewNumber = true;
        if (!txtScreen.getText().equals("ERROR")) {
            logic.setMemory(new BigDecimal(txtScreen.getText()));
        }
    }//GEN-LAST:event_btMSActionPerformed

    private void btClearLastNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearLastNumActionPerformed
            // TODO add your handling code here:
        
        if (txtScreen.getText().equals("ERROR")) {
            setDefaultSetting();
        }else{
            String screen=txtScreen.getText();
            if(screen.length()==1){
                screen="0";
            }else{
              screen=screen.substring(0,screen.length()-1);  
            }
            
            txtScreen.setText(screen);
        }
    }//GEN-LAST:event_btClearLastNumActionPerformed

    private void btCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCEActionPerformed
        // TODO add your handling code here:
        if(logic.getOperator()==null||txtScreen.getText().equals("ERROR")){
            setDefaultSetting();
        }else{
            txtScreen.setText("0");
        }
    }//GEN-LAST:event_btCEActionPerformed

    private void btCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCActionPerformed
        // TODO add your handling code here:
        setDefaultSetting();
    }//GEN-LAST:event_btCActionPerformed

    /**
     * @param args the command line arguments
     */
    //write number is pressed on screen
    void pressNumber(String number) {
        //notice that user is inputing number
        isInputingNumber = true;
        //handle error because of divide by zero
        if (divideByZero) {
            divideByZero = false;
            setDefaultSetting();
        }
        //if screen display 0 or flag canInputNewNumber==true
        if (txtScreen.getText().equals("0") || canInputNewNumber == true) {
            //set bufferScreenText = null when there was an error by press sqrt
            if(bufferScreenText!=null) bufferScreenText=null;
            //set screen text by value of button user just input
            txtScreen.setText(number);
            canInputNewNumber = false;
        } 
        //merge number
        else {
            txtScreen.setText(txtScreen.getText() + number);
        }
    }

    void pressOperator(String operator) {
        //allow user to input new number
        canInputNewNumber = true;
        //handle error because of divide by zero
        if (divideByZero) {
            setDefaultSetting();
            divideByZero = false;
        }
        //when user inputed number or user press equal button to calculate or screen display "0"
        if (isInputingNumber || isPressEqualForCal||txtScreen.getText().equals("0")) {
            isInputingNumber = false;
            isPressEqualForCal = false;
            //if there was error by button sqrt
            if(bufferScreenText!=null){
                //pass data to logic side by "bufferScreenText"
                logic.getData(bufferScreenText);
                bufferScreenText=null;
            }else{
                //pass data to logic side by screen text
                logic.getData(txtScreen.getText());
            }
            //if logic side get enought data
            if (logic.getNum1() != null && logic.getNum2() != null && logic.getOperator() != null) {
                //try catch to handle error divide by zero
                try {
                    //calculate
                    logic.calculate();
                    //remove redundant zero 
                    String result = removeRedundantZeroAfterDot(logic.getResult().toString());
                    //display result to screen
                    txtScreen.setText(result);
                    logic.setNum2(null);
                    logic.setNum1(logic.getResult());
                } catch (ArithmeticException e) {
                    //flag divieByZero = true
                    divideByZero = true;
                    txtScreen.setText("ERROR");
                }

            }
        }
        //pass operator value to logic side
        logic.setOperator(operator);
    }

    String removeRedundantZeroAfterDot(String result) {
        //do nothing if number does not contain "."
        if (!result.contains(".")) {
            return result;
        }
     //   0.1230
        int index = -1;
        //specify position number which is before the first redundant zero
        for (int i = result.length() - 1; i >= 0; i--) {
            if (result.charAt(i) != '0') {
                index = i;
                break;
            }
        }  
        //remove all redundant zero 
        String newResult = result.substring(0, index + 1);
        //if remove "." if there is no number after "."
        if (result.indexOf(".") == newResult.length() - 1) {
            newResult = newResult.replace(".", "");
        }
        return newResult;
    }

    void setDefaultSetting() {
        
        txtScreen.setText("0");
        logic.setNum1(null);
        logic.setNum2(null);
        logic.setResult(null);
      //  logic.setMemory(new BigDecimal("0"));
        logic.setFirstCalculate(true);
        logic.setOperator(null);
        canInputNewNumber = true;
        isInputingNumber = false;
        isPressEqualForCal = false;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt1OverX;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btC;
    private javax.swing.JButton btCE;
    private javax.swing.JButton btChangeSign;
    private javax.swing.JButton btClearLastNum;
    private javax.swing.JButton btDivide;
    private javax.swing.JButton btDot;
    private javax.swing.JButton btEqual;
    private javax.swing.JButton btMC;
    private javax.swing.JButton btMR;
    private javax.swing.JButton btMS;
    private javax.swing.JButton btMinus;
    private javax.swing.JButton btMminus;
    private javax.swing.JButton btMplus;
    private javax.swing.JButton btMultiply;
    private javax.swing.JButton btPercent;
    private javax.swing.JButton btPlus;
    private javax.swing.JButton btSqrt;
    private javax.swing.JTextField txtScreen;
    // End of variables declaration//GEN-END:variables
}
